server:
  port: 8705
spring:
  application:
    name: education-resume
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.108.230:3306/education_resume_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  config:
    import: nacos:education-common.yml
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.108.230:8848
        username: nacos
        password: nacos
      config:
        server-addr: 192.168.108.230:8848
        username: nacos
        password: nacos
